### ISSUE TITLE
Web console doesn't display all columns 

### ISSUE THREAD

**Issue by bziobrowski** [questdb/ui#121]
When scrolling down on a large result set, ui sometimes doesn't show values for all columns .

Run :

```sql
CREATE TABLE uitest (
  id SYMBOL capacity 256 CACHE,
  linkedId SYMBOL capacity 256 CACHE,
  description STRING,
  other STRING,
  timestamp TIMESTAMP,
  whenEndMs LONG
) timestamp (timestamp) PARTITION BY DAY;


insert into uitest 
select 'id' || (x%100),
  'linked-generated-id' || (x%300),
  rnd_str(200, 500,0),
  rnd_str(20,50,0),
  x::timestamp, 
  rnd_long()
from long_sequence(9000);

selecT * from uitest;
```

then scroll down to the bottom, scroll to the right to see last columns and then scroll up a few screens. 
The last few columns won't have any data displayed even though it was sent from the backend.  
If you then scroll to the left and back to right, data will appear. 

<img width="975" alt="missing_col" src="https://user-images.githubusercontent.com/26925920/230356002-0a9cb791-b584-4924-879f-ab6bfe9f6309.png">

**Comment by bluestreak01** [comment]
this issue is fixed


https://github.com/questdb/ui/assets/7276403/2ebf8051-c894-4181-b37e-ce7c7b576a29
