### ISSUE TITLE
QuestDB Showing Wrong Values on Web UI Results

### ISSUE THREAD

**Issue by superichmann** [questdb/ui#167]
Go to https://demo.questdb.io/
`SELECT timestamp_sequence(to_timestamp('2013-01-01T00:00:00','yyyy-MM-ddTHH:mm:ss'),  86400000000L) as date FROM long_sequence(1700)`
See results towards the end. 
Download csv to compare to actual values. there is a difference.

Windows machine, tested on chrome,edge,firefox.

**Comment by bluestreak01** [comment]
timestamp sequence is unstable in that it does not have "state". Grid fetches 1000 rows at a time and on every fetch this sequence is reset to start.

This should not be an issue with persisted data.
