### ISSUE TITLE
Application crashes with empty Grid in development mode

### ISSUE THREAD

**Issue by insmac** [questdb/ui#182]
Steps to reproduce: (note: this happens in _development_ mode only)

1. Make sure there are no records and no columns in the grid (i.e. refresh the Console).
2. Go to any page other than the sql editor: Import or Settings.
3. Go back to the editor. The application will crash with the following JavaScript error in Developer Console:
<img width="579" alt="CleanShot 2023-08-07 at 12 56 22@2x" src="https://github.com/questdb/ui/assets/1871646/4aa0dec3-1e23-4131-bb69-ab03c0bd5306">

The issue seems to be caused by this code in grid.js

```
function setFocusedColumn(columnIndex) {
    if (columnIndex !== -1) {
      focusedColumnIndex = columnIndex
      const cell = focusedColumnIndex < freezeLeft ? focusedRowContainerLeft.childNodes[focusedColumnIndex] : focusedRowContainer.childNodes[focusedColumnIndex % visColumnCount]
      cell.columnIndex = focusedColumnIndex
      setFocusedCell(cell)
    }
  }
```
`cell` conditional (`focusedColumnIndex < freezeLeft`) evaluates to `false` and breaks down on `focusedColumnIndex % visColumnCount` which equals to `NaN`.

**Comment by argshook** [comment]
closed by #198
