### ISSUE TITLE
Add `DEDUP` statement to `Copy schema to clipboard` feature

### ISSUE THREAD

**Issue by insmac** [questdb/ui#184]
Currently, the `Copy schema to clipboard` feature that generates the SQL to create a table does not take deduplication keys into consideration (omits `DEDUP UPSERT keys(key1, key2)` from the statement). 

Solution: Add the statement if needed, along with a key list.

**Comment by jerrinot** [comment]
@insmac I just stumbled upon this. it would be great to have it fixed.
fwiw: I am not sure whether the web console should generate DDLs out of columnar metadata. shouldn't we rather have a server-side function for this?
