### ISSUE TITLE
Add variance functions to syntax highlighter

### ISSUE THREAD

**Issue by javier** [questdb/ui#203]
Three new functions are now supported for variance [see questdb/questdb/pull/3770](https://github.com/questdb/questdb/pull/3770).

`variance()`, `var_samp()`, `var_pop()`

Support should be added to the console

**Comment by argshook** [comment]
Hey @javier! This should be done in the `sql-grammer` repo. I submitted a PR here: https://github.com/questdb/sql-grammar/pull/27
