### ISSUE TITLE
Web Console removes any string (inclusive) between `<` and `>` in a table value

### ISSUE THREAD

**Issue by BaileyJM02** [questdb/ui#217]
When using the web-console, any string column that contains `<string>` is removed. I haven't tested but may also occur with `<>`. Therefore, with the example data set below, the output is given as: 

Current output:
| id | some_string_column |
| -- | ------------------ |
| abc123 | some-uuid-exampleother-uuid |

Expected output (and example data set):
| id | some_string_column |
| -- | ------------------ |
| abc123 | some-uuid-example\<seperator\>other-uuid |

P.S I've had to escape the string in markdown as simply putting \<abc> causes it to be removed from output. Could be the issue?

Thanks,
Bailey

**Comment by javier** [comment]
Easy way to test, just fire up questdb and execute 
```
select 'Hello<there>. This is not <great>'
```

**Comment by BaileyJM02** [comment]
Note from @javier in Slack, and a good catch. String outputs are being interpreted as HTML, that appears to be the route issue here 👍

**Comment by javier** [comment]
And just for fun, and to show this is the case
```
select 'Hello. This <marquee>should not happen</marquee>'
```
