### ISSUE TITLE
WebUI - Tables missing and unable to query

### ISSUE THREAD

**Issue by warnesey333** [questdb/ui#38]
### Describe the bug

After a fresh install on Centos 8 Stream (XFS Filesystem) the Web UI does not work. The tables list is empty (including telemetry) and I am unable to type in the query editor.

I have run the same install on Docker on the same machine (Overlay) and that works. However if I mount a volume, that also fails.

There are no obvious errors in the logs. Running queries from the rest endpoint gives mixed results:

**/exec?query=select * from table_1;** works as expected however
**/exec?query=tables;** returns an empty set, even though I have created tables and inserted data

### To reproduce

1) Fresh install on Centos 8 Stream with XFS
2) Load Web UI
3) Editor is locked, tables empty

### Expected Behavior

Normal working behaviour expected

### Environment

```markdown
- **QuestDB version**:6.2.1
- **OS**: Centos 8 Stream - 4.18.0-348.7.1.el8_5.x86_64
- **Browser**: Edge/Chrome
```

**Comment by argshook** [comment]
hey @warnesey333, i'm going through some of older issues of QuestDB web console and stumbled upon this one. Looks like this was fixed a while back, therefore i'll close the issue.

But please do feel free to reopen, if you still encounter the issue. Thanks!
