### ISSUE TITLE
[Console] Improve i18n for notifications

### ISSUE THREAD

**Issue by mpsq** [questdb/ui#60]
Currently, notifications show time in the format `HH:MM:SS`:

![2020-06-19-153902_grim](https://user-images.githubusercontent.com/5734722/85144473-18fce000-b243-11ea-9b84-a65a246cd07c.png)

We want instead to check the browser locales and display the time according to the user location/preferences. Date formatting should be done either natively (i18n module, cf. [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n) for documentation) or via [date-fns](https://date-fns.org/docs/Getting-Started).

**Comment by ManasMadan** [comment]
@mpsq Please assign this issue to me under hacktoberfest 2023. I Have Worked with i18n and date-fns before.
Thanks !

**Comment by msk4862** [comment]
@mpsq Gave it a try and raised a PR for this: https://github.com/questdb/ui/pull/207
Can you please take a look?

**Comment by oliver-daniel** [comment]
Hey @msk4862! Thanks for your PR. Be advised that the most active maintainers of this repo are myself, @argshook and @insmac.

@ManasMadan, sincere apologies for not getting to your comment sooner. If you're interested, I have another task in mind that surrounds `date-fns` and `i18n` that would be suitable for your experience, and may slot in well with Shoaib's contribution. Would you like me to describe it to you, and if you're interested, set up an issue and assign it to you?

Happy Hacktober!

**Comment by ManasMadan** [comment]
@oliver-daniel No worries I would love to work on a issue

**Comment by oliver-daniel** [comment]
Hey @ManasMadan, thanks for your patience!

What do you think of working on the functionality of the Chart panel, as in #45?

To keep the scope of your work doable within Hacktober, I would recommend either working on the fix described in the issue, or laying out another singular improvement. For example, if you'd like to continue in the timestamp area, I'd personally be thrilled to see the ability to modify the format of charted timestamps.
I'm happy to work with you to lay out the scope of your contribution.

**Comment by ManasMadan** [comment]
@oliver-daniel I can work with the timestamp format thing.
after that i can work on issue #45 if someone does not complete it
