### ISSUE TITLE
when execute ` yarn start`, errors happens!

### ISSUE THREAD

**Issue by theseusyang1** [questdb/ui#70]
Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///Users/the/ui/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'

**Comment by argshook** [comment]
Hello @theseusyang1, thanks for filling the issue and sorry you had trouble!

The error you posted indicates to me that you were possibly running `yarn start` with node version newer than the one this project is using, which is `16.13.1` (as indicated by [.nvmrc file](https://github.com/questdb/ui/blob/main/.nvmrc))

Please see [this section of readme](https://github.com/questdb/ui/tree/main/packages/web-console#2-bootstrap-dependencies) which should help with dealing with different node versions.

Meanwhile i am closing this issue, but do feel free to reopen (or open a new one) if you still have troubles bootstrapping this project.

Cheers!

p.s. we're aware that node already has newer versions, but have not yet upgraded this project to use them. As always, we're open to contributions, so if you, dear reader (whoever you may be), would like to contribute, please do so!
